# Use Microsoft devcontainers alpine base
FROM mcr.microsoft.com/devcontainers/javascript-node:20
# Install git, nodejs, yarn and dependencies
RUN apt-get update && apt-get -y install yarn --no-install-recommends